---
- import_playbook: ansible.yml
- hosts: localhost
  vars:
    qtver: 5.11.2
    url: https://download.qt.io/archive/qt/5.11/5.11.2/qt-opensource-linux-x64-5.11.2.run
    file: qt-opensource-linux-x64-5.11.2.run
    hash: md5:974fda61267cfb6e45984ee5f0a285f8
    install_path: /opt/qt5.11.2
    packages: qt.qt5.5112.gcc_64
  tasks:
  - name: Download Qt
    become: yes
    become_user: ci
    get_url:
      url: "{{url}}"
      dest: /host/download/{{file}}
      checksum: "{{hash}}"
  - name: Check Installation
    stat:
       path: "{{ install_path }}"
    register: qt_installation_result
  - name: Show packages
    shell: DISPLAY="" /host/qtci/bin/extract-qt-installer --list-packages /host/download/{{file}} > /host/qtci/meta/qt-{{qtver}}-packages.txt
    when: qt_installation_result.stat.exists == False
  - name: Install Qt
    shell: DISPLAY="" QT_CI_PACKAGES="{{packages}}" /host/qtci/bin/extract-qt-installer /host/download/{{file}} {{install_path}}
    when: qt_installation_result.stat.exists == False
  - name: QT Path in .bashrc
    blockinfile:
      dest: /home/ci/.bashrc
      marker_begin: "QT_PATH_BEGIN"
      marker_end: "QT_PATH_END"
      block: |
        export PATH={{install_path}}/{{qtver}}/gcc_64/bin:$PATH
